/* THE OPENING QUESTIONS, DERIVED FROM THIS STOCK.
   ────────────────────────────────────────────────────────────────
   These were three near-fixed strings with the score interpolated
   into one of them. That had a specific failure: "Explain the debt
   number" was offered for every stock, including the ones whose debt
   figure the source does not report. Tapping it asked the model
   about a number that is not in its context, and the honest answer —
   "that is not available" — reads as the assistant being broken when
   it was the suggestion that was wrong.

   So every candidate below is generated from the payload the page is
   already holding, and each one carries a GUARD: it is only offered
   when the number it asks about actually exists. A suggested
   question the model cannot answer is worse than no suggestion.

   Weighted, and the heaviest three win, so the panel opens on the
   most interesting true things about THIS stock rather than the
   first three in a list. Same construction as src/lib/observe.js,
   which picks the bob's observation the same way — one idiom for
   "say the most useful true thing", used twice.

   Nothing here is generated by a model. Templates over numbers
   already on screen cost nothing, cannot be wrong, and cannot spend
   the free-tier quota that the actual answers need. */

/**
 * @returns {string[]} three questions, always answerable from the
 *   grounded context the chat route builds.
 */
export function startersFor(run) {
  if (!run) return ['What does this score mean?'];
  const { quote, model, sim, news } = run;
  const c = [];

  const push = (weight, text) => c.push({ weight, text });

  /* ── the gap, when there is one worth asking about ──
     The headline of the whole product, so it outranks everything. */
  const userPct = model?.userProb != null ? Math.round(model.userProb * 100) : null;
  const modelPct = model?.modelProb != null ? Math.round(model.modelProb * 100) : null;
  if (userPct !== null && modelPct !== null) {
    const gap = userPct - modelPct;
    if (Math.abs(gap) >= 10) {
      push(
        100,
        gap > 0
          ? `Why is the simulation less confident than me?`
          : `Why is the simulation more confident than me?`
      );
    } else if (Math.abs(gap) <= 3) {
      push(70, `We agree at about ${modelPct}% — what is driving that?`);
    }
  }

  /* ── the weakest component, named ──
     Guarded on the component existing AND having a real score, which
     is what the old "Explain the debt number" failed to check. */
  const scored = (model?.components ?? []).filter(
    (x) => x.key !== 'dataQuality' && Number.isFinite(x.score)
  );
  const weakest = [...scored].sort((a, b) => a.score - b.score)[0];
  const strongest = [...scored].sort((a, b) => b.score - a.score)[0];
  if (weakest && weakest.score <= 4) {
    push(95, `Why did ${weakest.name.toLowerCase()} score only ${weakest.score}?`);
  } else if (strongest && strongest.score >= 8) {
    push(60, `What makes ${strongest.name.toLowerCase()} score ${strongest.score}?`);
  }

  /* ── a metric the source simply does not have ──
     Worth surfacing precisely because most tools hide it. Only
     offered when something really is missing. */
  const missing = (model?.components ?? []).flatMap((x) => x.missing ?? []);
  if (missing.length) {
    push(80, `Why is ${missing[0]} not available?`);
  }

  /* ── the width, when it is genuinely wide ──
     The one quantity the backtest validates, so a question about it
     is always answerable and always relevant. */
  const widthPct = model?.width != null ? Math.round(model.width * 100) : null;
  if (widthPct !== null && widthPct >= 70) {
    push(90, `Why is the range as wide as ${widthPct}% of my money?`);
  } else if (widthPct !== null && widthPct <= 45) {
    push(55, `Why is the range comparatively narrow here?`);
  }

  /* ── thin history ── */
  if (quote?.daysAvailable && quote.daysAvailable < 400) {
    push(85, `Does ${quote.daysAvailable} days of history make this less reliable?`);
  }

  /* ── SIP genuinely helps ── */
  const imp = model?.suggestion?.p10ImprovementPct;
  if (Number.isFinite(imp) && imp >= 20) {
    push(65, `How does spreading it over twelve months cut the worst case by ${imp}%?`);
  }

  /* ── news exists, and is deliberately not in the score ── */
  if (news?.items?.length) {
    push(50, `There are ${news.items.length} headlines here — why are they not in the score?`);
  }

  /* ── the odds the simulation counted ── */
  const lose20 = model?.odds?.['12M']?.lose20;
  if (Number.isFinite(lose20) && lose20 >= 0.05) {
    push(75, `What is behind the ${Math.round(lose20 * 100)}% chance of losing 20%?`);
  }

  /* ── always-available fallbacks ──
     Low weight, so they only appear when nothing more specific
     applies — but they guarantee three buttons on every stock. */
  push(30, 'What would change this answer?');
  push(25, `How was ${quote?.ticker ?? 'this'} volatility calculated?`);
  push(20, 'What can this model actually see?');

  return c
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 3)
    .map((x) => x.text);
}
